/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_hotel;

import com.sun.org.apache.bcel.internal.generic.Select;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.select;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class chekin extends javax.swing.JFrame {
    private String kode,type,bed,roomtype,roomno,price;
    private int harga,bayar1,bayar2,kembalian1,kurang;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    public chekin() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        SimpleDateFormat myformat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal=Calendar.getInstance();
        tgl_chekin.setText(myformat.format(cal.getTime()));
        
        SimpleDateFormat clformat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cali=Calendar.getInstance();
        tgl_chekout.setText(clformat.format(cal.getTime()));
    }
// public void roomdetails(){
//        nokamar.removeAllItems();
//        hargatotal.setText("");
//        bed=(String)nokamar.getSelectedItem();
//        roomtype=(String)tipekamar.getSelectedItem();
//        
//        try {
////            ResultSet rs=stat.executeQuery("select *from kamar_hotel where No_kamar='"+bed+"'");
////            ResultSet rs=Select.getData("select *from kamar_hotel where No_Kamar='"+bed"' and and Status='Kosong'");
//              java.sql.Statement stm = con.createStatement();
//              java.sql.ResultSet sql = stm.executeQuery("select * from kamar_hotel where No_Kamar='"+bed+"' and Jenis_Kamar='"+tipekamar+"'");
//
//
//            while(rs.next()){
//                nokamar.addItem(rs.getString(1));
//            }
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//     
// }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nope_plg = new javax.swing.JTextField();
        nama_pelanggan = new javax.swing.JTextField();
        combox_jkplg = new javax.swing.JComboBox<>();
        lama = new javax.swing.JTextField();
        nokamar = new javax.swing.JComboBox<>();
        tipekamar = new javax.swing.JComboBox<>();
        id_pelanggan = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        hargatotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btbayar = new javax.swing.JLabel();
        lamainap = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tgl_chekout = new javax.swing.JTextField();
        tgl_chekin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hargakamar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, 80));

        nope_plg.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        nope_plg.setBorder(null);
        jPanel1.add(nope_plg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 320, 410, 60));

        nama_pelanggan.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        nama_pelanggan.setBorder(null);
        jPanel1.add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 420, 60));

        combox_jkplg.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        combox_jkplg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(combox_jkplg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 270, 60));

        lama.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lama.setBorder(null);
        lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaActionPerformed(evt);
            }
        });
        jPanel1.add(lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 820, 120, 50));

        nokamar.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        nokamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM001", "KM002", "KM003", "KM004", "KM005", "KM006", "KM007", "KM008", "KM009", "KM010" }));
        nokamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokamarActionPerformed(evt);
            }
        });
        jPanel1.add(nokamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 500, 250, 60));

        tipekamar.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        tipekamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe Room", "Double Room", "Superior Room", "Executive Room" }));
        tipekamar.setBorder(null);
        tipekamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipekamarActionPerformed(evt);
            }
        });
        jPanel1.add(tipekamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 500, 280, 60));

        id_pelanggan.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        id_pelanggan.setBorder(null);
        jPanel1.add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 210, 60));

        bayar.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        bayar.setBorder(null);
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 680, 240, 50));

        kembalian.setEditable(false);
        kembalian.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        kembalian.setBorder(null);
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 880, 260, 50));

        hargatotal.setEditable(false);
        hargatotal.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        hargatotal.setBorder(null);
        jPanel1.add(hargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 680, 270, 50));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 880, 280, 70));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, 70));

        btbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbayarMouseClicked(evt);
            }
        });
        jPanel1.add(btbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 880, 280, 70));

        lamainap.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lamainap.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        lamainap.setBorder(null);
        lamainap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lamainapMouseClicked(evt);
            }
        });
        jPanel1.add(lamainap, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 100, 60));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 950, 160, 70));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 210, 70));

        tgl_chekout.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        tgl_chekout.setBorder(null);
        jPanel1.add(tgl_chekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 690, 150, 50));

        tgl_chekin.setEditable(false);
        tgl_chekin.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        tgl_chekin.setBorder(null);
        jPanel1.add(tgl_chekin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/chek in baru.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        hargakamar.setText("hargakamar");
        jPanel1.add(hargakamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 860, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void nokamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokamarActionPerformed

    }//GEN-LAST:event_nokamarActionPerformed

    private void tipekamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipekamarActionPerformed
        // TODO add your handling code here:
//        roomdetails();
        kode = (String) tipekamar.getSelectedItem();
        if (kode == "Standard"){
            harga = 250000;
        }
        else if (kode == "Deluxe Room"){
            harga = 300000;
        }
        else if (kode == "Double Room"){
            harga = 350000;
        }
        else if (kode == "Superior Room"){
            harga = 450000;
        }
        else if (kode == "Executive Room"){
            harga = 550000;
        }
        
        hargakamar.setText(String.valueOf(harga));
        Integer value = (Integer)lamainap.getValue();
        hargatotal.setText(String.valueOf(harga*value));
    }//GEN-LAST:event_tipekamarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new register().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked
//public void id_auto(){ //Kode Otomatis
// try{
// String sql = "select max(right(id,3)) as id from pelanggan";
// stat=con.createStatement();
// rs=stat.executeQuery(sql);
// 
// while (rs.next()){
// if (rs.first() == false){
//  id_pelanggan.setText("PL001");
// }
// else{
// rs.last();
// int set_id = rs.getInt(1)+1;
// String no = String.valueOf(set_id);
// int id_next = no.length();
// for (int a = 0 ; a < 3 - id_next; a++){
// no = "0" + no;
// }
// id_pelanggan.setText("PL" + no);
// 
// }
// } 
// } catch (SQLException ex) {
// Logger.getLogger(chekin.class.getName()).log(Level.SEVERE, null, ex);
// }
// }
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
    stat = con.createStatement();
    stat.executeUpdate("INSERT INTO pelanggan VALUES('" +id_pelanggan.getText() + "','"
        + nama_pelanggan.getText()+ "','"
        + combox_jkplg.getSelectedItem()+ "','"
        + nope_plg.getText()+ "','"
        + tgl_chekin.getText()+ "','"
        + tgl_chekout.getText()+ "','"
        + lamainap.getValue()+ "','"
        + tipekamar.getSelectedItem()+ "','"
        + nokamar.getSelectedItem()+ "','"
        + hargatotal.getText()+ "','"
        + bayar.getText()+ "','"
        + kembalian.getText() + "')");
    JOptionPane.showMessageDialog(null, "Simpan Berhasil");
    id_pelanggan.setText("");
    nama_pelanggan.setText("");
    nope_plg.setText("");
    lamainap.setValue(1);
    hargatotal.setText("");
    bayar.setText("");
    kembalian.setText("");
  } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Data ada yg sama");
    e.printStackTrace();
  }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbayarMouseClicked
        // TODO add your handling code here:
        int satu = (int) lamainap.getValue();
        SimpleDateFormat clformat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cali=Calendar.getInstance();
        cali.add(Calendar.DATE,+satu);
        tgl_chekout.setText(clformat.format(cali.getTime()));
        
        bayar1 = Integer.parseInt(bayar.getText());
        bayar2 = Integer.parseInt(hargatotal.getText());
        kembalian1 = bayar1-bayar2;
        kurang = bayar2-bayar1;
        if(bayar1<bayar2){
            javax.swing.JOptionPane.showMessageDialog(null, "Mohon Maaf Uang Anda Kurang Rp. "+kurang);
            kembalian.setText("");
        }
        else{
            kembalian.setText(""+kembalian1);
            javax.swing.JOptionPane.showMessageDialog(null, "Pembayaran Berhasil");
        }
    }//GEN-LAST:event_btbayarMouseClicked

    
    
    private void lamainapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamainapMouseClicked
        // TODO add your handling code here:
        
        
        
////        clformat.setTime(sdf.parse(dt));
//        cali.add(Calendar.satu = (int));  // number of days to add
//        dt = sdf.format(c.getTime());  // dt is now the new date
        
        
    }//GEN-LAST:event_lamainapMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new chekout().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chekin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JLabel btbayar;
    private javax.swing.JComboBox<String> combox_jkplg;
    private javax.swing.JTextField hargakamar;
    private javax.swing.JTextField hargatotal;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField lama;
    private javax.swing.JSpinner lamainap;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JComboBox<String> nokamar;
    private javax.swing.JTextField nope_plg;
    private javax.swing.JTextField tgl_chekin;
    private javax.swing.JTextField tgl_chekout;
    private javax.swing.JComboBox<String> tipekamar;
    // End of variables declaration//GEN-END:variables
}
