/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_hotel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class room extends javax.swing.JFrame {
Connection con;
    Statement stat;
    ResultSet rs;
    String sql,kode;
    int harga;
    public room() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txthargakamar = new javax.swing.JTextField();
        txtnokamar = new javax.swing.JTextField();
        comboxtipekamar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblroom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setMinimumSize(new java.awt.Dimension(1519, 604));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txthargakamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargakamarActionPerformed(evt);
            }
        });
        jPanel1.add(txthargakamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 340, 50));
        jPanel1.add(txtnokamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 340, 70));

        comboxtipekamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe Room", "Double Room" }));
        comboxtipekamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxtipekamarActionPerformed(evt);
            }
        });
        jPanel1.add(comboxtipekamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 340, 60));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel3.setText("Harga");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 280, 100));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel4.setText("No Kamar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 260, 100));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel5.setText("Tipe Kamar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 280, 100));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 110, 50));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 110, 50));

        jButton2.setText("Input");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 150, 70));

        tblroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Kamar", "Jenis Kamar", "Harga", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblroomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblroom);
        if (tblroom.getColumnModel().getColumnCount() > 0) {
            tblroom.getColumnModel().getColumn(0).setResizable(false);
            tblroom.getColumnModel().getColumn(1).setResizable(false);
            tblroom.getColumnModel().getColumn(2).setResizable(false);
            tblroom.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 870, 590));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bt Kembali.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String status;
        status = "Kosong";
        try {
    stat = con.createStatement();
    stat.executeUpdate("INSERT INTO kamar_hotel VALUES('" +txtnokamar.getText() + "','"
        + comboxtipekamar.getSelectedItem()+ "','"
        + txthargakamar.getText()+ "','"
        + status + "')");
    JOptionPane.showMessageDialog(null, "Simpan Berhasil");
    txtnokamar.setText("");
    txthargakamar.setText("");


  } catch (Exception e) {
    e.printStackTrace();
  }
    }//GEN-LAST:event_jButton2ActionPerformed

    void tampildata(){
DefaultTableModel tbl=new DefaultTableModel();
tbl.addColumn("No Kamar");
tbl.addColumn("Jenis Kamar");
tbl.addColumn("Harga");
tbl.addColumn("Status");

try{
String sql="select*from kamar_hotel";
stat=con.createStatement();
rs=stat.executeQuery(sql);
while(rs.next()){
tbl.addRow(new Object[]{rs.getString(1),rs.getString(2),
rs.getInt(3),rs.getString(4)});
}
tblroom.setModel(tbl);
}catch(Exception e){}
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tampildata();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboxtipekamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxtipekamarActionPerformed
        // TODO add your handling code here:
        String fasilitas;
        kode = (String) comboxtipekamar.getSelectedItem();
        if (kode == "Standard"){
            harga = 250000;
            
        }
        else if (kode == "Deluxe Room"){
            harga = 500000;
        }
        else{
            harga=350000;
        }
        
        txthargakamar.setText(String.valueOf(harga));
    }//GEN-LAST:event_comboxtipekamarActionPerformed

    private void txthargakamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargakamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargakamarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tblroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblroomMouseClicked
        // TODO add your handling code here:
        try {
 
int row =tblroom.getSelectedRow();
String tabel_klik=(tblroom.getModel().getValueAt(row, 0).toString());
java.sql.Statement stm = con.createStatement();
java.sql.ResultSet sql = stm.executeQuery("select * from kamar_hotel where No_Kamar='"+tabel_klik+"'");
 if(sql.next()){
 String nokamar = sql.getString("No_Kamar");
 txtnokamar.setText(nokamar);
 String tipekamar = sql.getString("Jenis_Kamar");
 comboxtipekamar.setSelectedItem(tipekamar);
 String hrg = sql.getString("Harga");
txthargakamar.setText(hrg);
 
 }
} catch (Exception e) {}
    }                                         

                                           

    void deletedata(){
try {
stat = con.createStatement();
stat.executeUpdate("Delete from kamar_hotel where No_Kamar= '" +txtnokamar.getText() + "'");
 JOptionPane.showMessageDialog(null, "Delete Berhasil");
 txtnokamar.setText("");
 comboxtipekamar.setSelectedItem("");
 txthargakamar.setText("");
 
 } catch (Exception e) {
 e.printStackTrace();
 } 
    }//GEN-LAST:event_tblroomMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        deletedata();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboxtipekamar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblroom;
    private javax.swing.JTextField txthargakamar;
    private javax.swing.JTextField txtnokamar;
    // End of variables declaration//GEN-END:variables
}
